backend:
  name: git-gateway
  branch: main
media_folder: "site/static/images" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit

  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Default Lander"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Intro", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Contact", name: contact, widget: object, fields: [
              {label: "Button", name: "button", widget: string}]}
          - {label: "Newsletter", name: newsletter, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Button", name: "button", widget: "text"}]}
      - file: "site/content/landera/_index.md"
        label: "Lander A"
        name: "landera"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Intro", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Contact", name: contact, widget: object, fields: [
              {label: "Button", name: "button", widget: string}]}
          - {label: "Newsletter", name: newsletter, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Button", name: "button", widget: "text"}]}
      - file: "site/content/landera/_index.md"
        label: "Lander B"
        name: "landerb"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Intro", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Contact", name: contact, widget: object, fields: [
              {label: "Button", name: "button", widget: string}]}
          - {label: "Newsletter", name: newsletter, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Button", name: "button", widget: "text"}]}
      - file: "site/content/landera/_index.md"
        label: "Lander C"
        name: "landerc"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Intro", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Contact", name: contact, widget: object, fields: [
              {label: "Button", name: "button", widget: string}]}
          - {label: "Newsletter", name: newsletter, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Button", name: "button", widget: "text"}]}
  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "site/hugo.toml"
        label: Hugo Config
        name: config
        editor:
          preview: false
        fields:
          - {label: Site Title for Browser Tab, name: title, widget: string}
          - label: Params
            name: params
            widget: object
            fields:
              - label: Open Graph Image
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
